/* F-3 R2-2 build-time keymap dump (de-fork).
 *
 * Emits windows/tsf/nabicloud_builtin_keymaps.h : the ASCII-key -> jamo map
 * (table id 0, keys 0x21..0x7E) for each pristine builtin keyboard, by calling
 * the engine-internal hangul_keyboard_map_to_char ONCE at build time. The shell
 * then owns this data (ShellKeymapLookup) and stops importing map_to_char at
 * runtime -- a non-pristine internal symbol the de-fork cuts (import gate).
 *
 * Golden-frozen: the generated header is committed; gate_shell_keymap_equiv
 * re-runs map_to_char and asserts byte-equivalence, so any engine drift (e.g.
 * the R4 vanilla 41c702f swap) is caught instead of silently diverging.
 *
 * ASCII-only TU (mirrors editor_jsc_dump.c). Built against the engine tree by
 * dump_builtin_keymaps.bat; output redirected to the header path.
 */
#include <stdio.h>

#include "hangul.h"
#include "hangulinternals.h"   /* hangul_keyboard_map_to_char (internal, non-static) */

/* internal-meta (internal header, non-static) -- declared like the shell does. */
int  hangul_keyboard_get_type(const HangulKeyboard* keyboard);
bool hangul_keyboard_get_flag(const HangulKeyboard* keyboard, unsigned int option);

/* Pristine libhangul builtins (NabiCloud.cpp s_keyboards == hangul_builtin_keyboards). */
static const char* const kBuiltins[] = {
    "2", "2y", "39", "3f", "3y", "ahn", "3s", "32", "ro",
};
#define NB ((int)(sizeof(kBuiltins) / sizeof(kBuiltins[0])))

#define KEY_LO 0x21u
#define KEY_HI 0x7Eu          /* inclusive; shell domain = MapsToJamo/keycap 0x21..0x7E */
#define KEY_N  (KEY_HI - KEY_LO + 1u)   /* 94 */

int main(void)
{
    int i;
    unsigned key;

    hangul_keyboard_list_init(NULL);   /* register builtins into the global list */

    printf("/* AUTO-GENERATED by shared/engine/tests/dump_builtin_keymaps.c -- DO NOT EDIT.\n");
    printf(" * F-3 R2-2 de-fork: shell-owned keymap for pristine builtins (map_to_char cut).\n");
    printf(" * Regenerate: shared/engine/tests/dump_builtin_keymaps.bat ; verify: gate_shell_keymap_equiv. */\n");
    printf("#pragma once\n\n");
    printf("/* key index = ascii - 0x%02X ; value = table-0 jamo (U+11xx / ASCII), 0 = unmapped. */\n", KEY_LO);
    printf("#define NABICLOUD_BUILTIN_KEYMAP_LO 0x%02Xu\n", KEY_LO);
    printf("#define NABICLOUD_BUILTIN_KEYMAP_HI 0x%02Xu\n", KEY_HI);
    printf("#define NABICLOUD_BUILTIN_KEYMAP_N  %uu\n\n", KEY_N);
    printf("/* type=hangul.h enum ; loose_order/abbrev = get_flag(LOOSE_ORDER/ABBREV). */\n");
    printf("struct NabicloudBuiltinKeymap { const char* id; int type; int loose_order; int abbrev; unsigned int map[NABICLOUD_BUILTIN_KEYMAP_N]; };\n\n");
    printf("static const struct NabicloudBuiltinKeymap kNabicloudBuiltinKeymaps[] = {\n");

    for (i = 0; i < NB; ++i)
    {
        const HangulKeyboard* kb = hangul_keyboard_list_get_keyboard(kBuiltins[i]);
        int ktype, klo, kab;
        if (kb == NULL)
        {
            fprintf(stderr, "DUMP_KEYMAP_FAIL: builtin '%s' not found\n", kBuiltins[i]);
            return 1;
        }
        ktype = hangul_keyboard_get_type(kb);
        klo = hangul_keyboard_get_flag(kb, HANGUL_KEYBOARD_FLAG_LOOSE_ORDER) ? 1 : 0;
        kab = hangul_keyboard_get_flag(kb, HANGUL_KEYBOARD_FLAG_ABBREV) ? 1 : 0;
        printf("    { \"%s\", %d, %d, %d, {", kBuiltins[i], ktype, klo, kab);
        for (key = KEY_LO; key <= KEY_HI; ++key)
        {
            unsigned int v = (unsigned int)hangul_keyboard_map_to_char(kb, 0, key);
            if ((key - KEY_LO) % 8u == 0u) printf("\n        ");
            printf("0x%04x,", v);
        }
        printf("\n    } },\n");
    }
    printf("};\n");
    printf("#define NABICLOUD_BUILTIN_KEYMAP_COUNT %d\n", NB);

    fprintf(stderr, "DUMP_KEYMAP_OK: %d builtins x %u keys\n", NB, KEY_N);
    return 0;
}
