/*
 * NabiCloud all-keyboards characterization harness (v2 W0).
 *
 * Purpose: freeze the EXACT observable behavior (commit/preedit per key, flush,
 * backspace, reset) of EVERY registered built-in keyboard, across the IC option
 * axis, so it can serve THREE roles from one source:
 *   (1) cross-engine equivalence oracle  - old engine output == future new
 *       (clean-slate) engine output for identical key sequences;
 *   (2) refactor regression gate          - any behavior change shows as a diff;
 *   (3) human test-sheet source           - input is the English physical key
 *       (ASCII), expected output is generated by the current engine, so a user
 *       can verify keyboards they do not personally use.
 *
 * It enumerates keyboards at RUNTIME via hangul_keyboard_list_get_count() /
 * _get_keyboard_id(), so it covers whatever is registered (all 14 built-ins).
 * External XML keyboards are intentionally OUT OF SCOPE for the frozen baseline
 * (non-deterministic per install dir); run with an external dir later via the
 * optional argv[1] to extend coverage without changing the committed baseline.
 *
 * The IC option axis (R-a of the adversarial review) dumps each keyboard at
 * default options AND with each option forced ON, because 3 built-ins
 * (2noshift / 2n9256 / 3-91-noshift) ship COMBI_ON_DOUBLE_STROKE on and that
 * option changes combine behavior - default-only golden misses it.
 *
 * ASCII-only on purpose (no UTF-8 BOM dependency, no CP949/C4819 trap).
 * Build: see tests\build_and_verify_all.bat (same source set as galmadeuli gate).
 */
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include "hangul.h"
#include "golden_util.h"   /* fmt() ucschar -> "U+XXXX" (extracted, Stage-B) */

/* current keyboard id + option config, read by make_ic(). -1 = leave default. */
static const char* g_kbd = "2";
static int g_ar = -1;   /* AUTO_REORDER          */
static int g_ds = -1;   /* COMBI_ON_DOUBLE_STROKE */
static int g_nc = -1;   /* NON_CHOSEONG_COMBI     */

static HangulInputContext* make_ic(void) {
    HangulInputContext* hic = hangul_ic_new(g_kbd);
    if (hic == NULL) return NULL;
    if (g_ar >= 0) hangul_ic_set_option(hic, HANGUL_IC_OPTION_AUTO_REORDER,          g_ar ? true : false);
    if (g_ds >= 0) hangul_ic_set_option(hic, HANGUL_IC_OPTION_COMBI_ON_DOUBLE_STROKE, g_ds ? true : false);
    if (g_nc >= 0) hangul_ic_set_option(hic, HANGUL_IC_OPTION_NON_CHOSEONG_COMBI,     g_nc ? true : false);
    return hic;
}

/* Run one key string start-to-flush, dumping commit+preedit per key. */
static void run_str(const char* name, const char* s) {
    char cbuf[512], pbuf[512];
    HangulInputContext* hic = make_ic();
    if (hic == NULL) { printf("T %s\n  FAIL new==NULL\n", name); return; }
    printf("T %s\n", name);
    for (const char* p = s; *p; ++p) {
        int processed = hangul_ic_process(hic, (unsigned char)*p) ? 1 : 0;
        fmt(hangul_ic_get_commit_string(hic), cbuf, sizeof(cbuf));
        fmt(hangul_ic_get_preedit_string(hic), pbuf, sizeof(pbuf));
        printf("  k=0x%02X p=%d commit=%s pre=%s\n",
               (unsigned)(unsigned char)*p, processed, cbuf, pbuf);
    }
    fmt(hangul_ic_flush(hic), cbuf, sizeof(cbuf));
    printf("  flush=%s\n", cbuf);
    hangul_ic_delete(hic);
}

/* Build a sequence, then backspace to empty, dumping preedit each step. */
static void run_backspace(const char* name, const char* s) {
    char pbuf[512];
    HangulInputContext* hic = make_ic();
    if (hic == NULL) { printf("T %s\n  FAIL new==NULL\n", name); return; }
    printf("T %s\n", name);
    for (const char* p = s; *p; ++p) hangul_ic_process(hic, (unsigned char)*p);
    fmt(hangul_ic_get_preedit_string(hic), pbuf, sizeof(pbuf));
    printf("  built pre=%s\n", pbuf);
    for (int i = 0; i < 12; ++i) {
        int ok = hangul_ic_backspace(hic) ? 1 : 0;
        fmt(hangul_ic_get_preedit_string(hic), pbuf, sizeof(pbuf));
        printf("  bs r=%d pre=%s\n", ok, pbuf);
        if (hangul_ic_is_empty(hic)) break;
    }
    hangul_ic_delete(hic);
}

/* Build partial, flush mid-composition, continue, flush again. */
static void run_flush_mid(const char* name, const char* a, const char* b) {
    char cbuf[512], pbuf[512];
    HangulInputContext* hic = make_ic();
    if (hic == NULL) { printf("T %s\n  FAIL new==NULL\n", name); return; }
    printf("T %s\n", name);
    for (const char* p = a; *p; ++p) hangul_ic_process(hic, (unsigned char)*p);
    fmt(hangul_ic_get_preedit_string(hic), pbuf, sizeof(pbuf));
    printf("  partA pre=%s\n", pbuf);
    fmt(hangul_ic_flush(hic), cbuf, sizeof(cbuf));
    printf("  flush1=%s\n", cbuf);
    for (const char* p = b; *p; ++p) hangul_ic_process(hic, (unsigned char)*p);
    fmt(hangul_ic_get_preedit_string(hic), pbuf, sizeof(pbuf));
    printf("  partB pre=%s\n", pbuf);
    fmt(hangul_ic_flush(hic), cbuf, sizeof(cbuf));
    printf("  flush2=%s\n", cbuf);
    hangul_ic_delete(hic);
}

/* Build, reset, verify empty, continue. */
static void run_reset(const char* name, const char* a, const char* b) {
    char cbuf[512], pbuf[512];
    HangulInputContext* hic = make_ic();
    if (hic == NULL) { printf("T %s\n  FAIL new==NULL\n", name); return; }
    printf("T %s\n", name);
    for (const char* p = a; *p; ++p) hangul_ic_process(hic, (unsigned char)*p);
    hangul_ic_reset(hic);
    fmt(hangul_ic_get_preedit_string(hic), pbuf, sizeof(pbuf));
    printf("  afterreset pre=%s empty=%d\n", pbuf, hangul_ic_is_empty(hic) ? 1 : 0);
    for (const char* p = b; *p; ++p) hangul_ic_process(hic, (unsigned char)*p);
    fmt(hangul_ic_flush(hic), cbuf, sizeof(cbuf));
    printf("  flush=%s\n", cbuf);
    hangul_ic_delete(hic);
}

/* Full fixed suite for the current g_kbd + option config. Input strings are
 * generic ASCII (same across keyboards) - this is characterization, not
 * "correct Hangul": we freeze whatever each keyboard does with these keys. */
static void run_suite(void) {
    {
        HangulInputContext* hic = make_ic();
        printf("## new_ok=%d\n", hic != NULL ? 1 : 0);
        if (hic) hangul_ic_delete(hic);
    }

    printf("## singles\n");
    for (int c = 0x21; c <= 0x7e; ++c) {
        char nm[16], s[2]; s[0] = (char)c; s[1] = 0;
        snprintf(nm, sizeof(nm), "s_%02X", c);
        run_str(nm, s);
    }

    printf("## curated\n");
    run_str("seq_word",   "gksrmf");
    run_str("seq_rep",    "fff");
    run_str("seq_rkk",    "rkk");
    run_str("seq_salm",   "tkfa");
    run_str("seq_gwa",    "rhk");
    run_str("seq_digits", "0123456789");
    run_str("seq_syms",   "!@#$%^&*()");
    run_str("seq_mixed",  "kf3if9");
    run_str("seq_dbl",    "kkffss");
    run_str("seq_long",   "mfsrnfdfj");
    run_str("seq_bracket","kf[sif[");

    printf("## backspace\n");
    run_backspace("bs_a", "rkk");
    run_backspace("bs_b", "tkfa");
    run_backspace("bs_c", "gksrmf");

    printf("## flushmid\n");
    run_flush_mid("fm_a", "kf", "sif");
    run_flush_mid("fm_b", "rkk", "ej");

    printf("## reset\n");
    run_reset("rs_a", "rkk", "sk");
    run_reset("rs_b", "gks", "rmf");
}

int main(int argc, char** argv) {
    (void)argc;
    (void)argv;

    printf("# nabicloud golden_all v1 (characterization, do not edit by hand)\n");
    printf("## extdir=(none) builtins-only baseline\n");

    unsigned n = hangul_keyboard_list_get_count();
    printf("## keyboard_count=%u\n", n);

    /* option configs: default + each option forced ON (R-a coverage). */
    struct { const char* tag; int ar, ds, nc; } cfgs[] = {
        { "def", -1, -1, -1 },
        { "ar1",  1, -1, -1 },
        { "ds1", -1,  1, -1 },
        { "nc1", -1, -1,  1 },
    };
    const unsigned ncfg = (unsigned)(sizeof(cfgs) / sizeof(cfgs[0]));

    for (unsigned i = 0; i < n; ++i) {
        const char* id = hangul_keyboard_list_get_keyboard_id(i);
        if (id == NULL) id = "(null)";
        for (unsigned ci = 0; ci < ncfg; ++ci) {
            g_kbd = id;
            g_ar = cfgs[ci].ar;
            g_ds = cfgs[ci].ds;
            g_nc = cfgs[ci].nc;
            printf("\n=== KBD idx=%u id=%s cfg=%s ===\n", i, id, cfgs[ci].tag);
            run_suite();
        }
    }

    printf("# end\n");
    return 0;
}
