/* RETIRED (dead archive, not built) -- see tests/RETIRED.md. Depended on the shin builtin
   oracle (nabicloud_shin_builtin_by_id) removed in F-3 R5 (2026-06-27). */
/* NabiCloud Sebeolsik Sin (신세벌, 3shin*) external-XML byte-fidelity verifier +
 * generator (B2 PROOF harness).
 *
 * B2 (2026-06-20): the 9 신세벌 keyboards were REMOVED from the engine builtins
 * (hangul_builtin_keyboards[] in hangulkeyboard.c) and now ship ONLY as external
 * body keyboards at shared/data/keyboards/3shin-*.xml. The 9 static const
 * HangulKeyboard definitions stay in hangulkeyboard.c as the byte-fidelity ORACLE,
 * reachable via nabicloud_shin_builtin_by_id().
 *
 * This harness has two modes, run back-to-back in main():
 *   GEN : for each of the 9 ids, mechanically emit 3shin-<id>.xml from the builtin
 *         oracle struct -- map[0] (128), combination[0/1/2], type, flags, addon
 *         columns, <option combi-on-double-stroke>. Emission is purely from the
 *         in-memory struct, so the XML cannot drift from the oracle by hand.
 *   VERIFY: reload each emitted XML through the SAME loader the DLL uses
 *         (hangul_keyboard_new_from_file) and FULL-FIELD byte-diff it against the
 *         oracle: id, type, map[0] all 128 entries, combination[0/1/2] (compared
 *         as sorted key/code sets -- the loader sorts, the builtin static array is
 *         in source order), flag[5], addon_key[0..2] strings, addon_value[0..3]
 *         arrays, addon_func[SYMBOL] presence. differential==0 means the
 *         transcription is exact. Any field mismatch is printed and fails the id.
 *
 * Reads internal struct fields, so it includes hangulinternals.h (compiled inside
 * the engine tree, like semoe_xml_verify.c). ASCII-only.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "hangul.h"
#include "hangulinternals.h"

#ifndef HANGUL_KEYBOARD_TABLE_SIZE
#define HANGUL_KEYBOARD_TABLE_SIZE 0x80
#endif

/* ★2026-06-25: 7개(2012/2015/m/p/p-yet/p2/p2-yet)는 V2 확장 XML 로 이관(libhangul-body →
 *   <jaso engine="v2"> jaso_layout). 더는 libhangul-body 형식이 아니므로 이 libhangul-오라클
 *   byte-fidelity 게이트 소관이 아니다(GEN 이 V2 XML 을 덮어쓰면 안 됨). 이관본의 무손실은
 *   V2 round-trip 게이트(cleanroom .../selftest_jaso_roundtrip.c: dump↔load↔C정본)가 담당.
 *   1995/2003 은 미이관(보류, V2 layout 없음) → 여기 잔류. 정본 = cleanroom/v2-promotion-plan.md. */
static const char* kIds[] = {
    "3shin-1995", "3shin-2003",
};
#define NSHIN (sizeof(kIds)/sizeof(kIds[0]))

/* type enum -> external-XML type string (loader on_element_start mapping). */
static const char* type_str(int type)
{
    switch (type) {
        case HANGUL_KEYBOARD_TYPE_JASO_SHIN:       return "jaso-shin";
        case HANGUL_KEYBOARD_TYPE_JASO_SHIN_SHIFT: return "jaso-shin-shift";
        case HANGUL_KEYBOARD_TYPE_JASO_SHIN_YET:   return "jaso-shin-yet";
        default:                                   return "jaso";
    }
}

/* Emit one combination[] block. Items carry .key == first<<16|second already. */
static void emit_combination(FILE* f, const HangulCombination* c, int id)
{
    if (c == NULL)
        return;
    fprintf(f, "    <combination id=\"%d\">\n", id);
    for (unsigned i = 0; i < c->size; ++i) {
        unsigned key   = (unsigned)c->table[i].key;
        unsigned first = (key >> 16) & 0xFFFF;
        unsigned second= key & 0xFFFF;
        unsigned result= (unsigned)c->table[i].code;
        fprintf(f, "        <item first=\"0x%04x\" second=\"0x%04x\" result=\"0x%04x\"/>\n",
                first, second, result);
    }
    fprintf(f, "    </combination>\n");
}

/* Emit one space-separated 0x.... ucschar list from a NUL-terminated array. */
static void emit_ucs_list(FILE* f, const ucschar* v)
{
    if (v == NULL)
        return;
    for (unsigned i = 0; v[i] != 0x0000; ++i)
        fprintf(f, "%s0x%04x", (i ? " " : ""), (unsigned)v[i]);
}

/* Generate 3shin-<id>.xml from the builtin oracle struct. */
static int gen_one(const char* dir, const HangulKeyboard* kb)
{
    char path[512];
    snprintf(path, sizeof(path), "%s/%s.xml", dir, kb->id);
    FILE* f = fopen(path, "wb");
    if (f == NULL) { printf("  GEN FAIL fopen %s\n", path); return 0; }

    fprintf(f, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
    fprintf(f, "<!--\n");
    fprintf(f, "  %s (Sebeolsik Sin / 신세벌) -- NabiCloud external body keyboard.\n", kb->name);
    fprintf(f, "  GENERATED by tests/shin_xml_verify.c from the builtin oracle\n");
    fprintf(f, "  (hangulkeyboard.c, nabicloud_shin_builtin_by_id). Do not edit by hand:\n");
    fprintf(f, "  the byte-diff gate proves this file round-trips field-for-field to the\n");
    fprintf(f, "  preserved builtin definition. License: LGPL-2.1-or-later (body data,\n");
    fprintf(f, "  3beol/yous gureum-1.11.1 verbatim).\n");
    fprintf(f, "-->\n");
    fprintf(f, "<hangul-keyboard id=\"%s\" type=\"%s\">\n\n", kb->id, type_str(kb->type));

    fprintf(f, "    <name>%s</name>\n", kb->name);
    fprintf(f, "    <name xml:lang=\"en\">%s</name>\n\n", kb->name);

    /* default_options: emit only the present options as explicit <option>. The
     * shin builtins carry COMBI_ON_DOUBLE_STROKE present+ON. */
    if (kb->default_options_present & NABICLOUD_KB_OPT_PRESENT_COMBI_ON_DOUBLE_STROKE) {
        bool on = (kb->default_options & NABICLOUD_KB_OPT_COMBI_ON_DOUBLE_STROKE) != 0;
        fprintf(f, "    <option name=\"combi-on-double-stroke\" value=\"%s\"/>\n",
                on ? "true" : "false");
    }
    if (kb->default_options_present & NABICLOUD_KB_OPT_PRESENT_AUTO_REORDER) {
        bool on = (kb->default_options & NABICLOUD_KB_OPT_AUTO_REORDER) != 0;
        fprintf(f, "    <option name=\"loose-order\" value=\"%s\"/>\n", on ? "true" : "false");
    }
    if (kb->default_options_present & NABICLOUD_KB_OPT_PRESENT_NON_CHOSEONG_COMBI) {
        bool on = (kb->default_options & NABICLOUD_KB_OPT_NON_CHOSEONG_COMBI) != 0;
        fprintf(f, "    <option name=\"non-choseong-combi\" value=\"%s\"/>\n", on ? "true" : "false");
    }
    fprintf(f, "\n");

    /* flags[5] -- emit all five explicitly so a false stays false on reload. */
    fprintf(f, "    <flags extended=\"%s\" galmadeuli=\"%s\" loose-order=\"%s\""
               " right-ou=\"%s\" no-added-ggeut=\"%s\"/>\n\n",
            kb->flag[HANGUL_KEYBOARD_FLAG_EXTENDED]       ? "true" : "false",
            kb->flag[HANGUL_KEYBOARD_FLAG_GALMADEULI]     ? "true" : "false",
            kb->flag[HANGUL_KEYBOARD_FLAG_LOOSE_ORDER]    ? "true" : "false",
            kb->flag[HANGUL_KEYBOARD_FLAG_RIGHT_OU]       ? "true" : "false",
            kb->flag[HANGUL_KEYBOARD_FLAG_NO_ADDED_GGEUT] ? "true" : "false");

    /* addon columns. Emit each present attribute; omit NULL ones so the reload
     * leaves the matching column NULL (oracle's NULL columns stay NULL). */
    fprintf(f, "    <addon");
    if (kb->addon_key[HANGUL_KEYBOARD_KEY_MOEUM] != NULL)
        fprintf(f, " moeum-key=\"%s\"", kb->addon_key[HANGUL_KEYBOARD_KEY_MOEUM]);
    if (kb->addon_key[HANGUL_KEYBOARD_KEY_SYMBOL] != NULL)
        fprintf(f, " symbol-key=\"%s\"", kb->addon_key[HANGUL_KEYBOARD_KEY_SYMBOL]);
    if (kb->addon_key[HANGUL_KEYBOARD_KEY_YETGEUL] != NULL)
        fprintf(f, " yetgeul-key=\"%s\"", kb->addon_key[HANGUL_KEYBOARD_KEY_YETGEUL]);
    if (kb->addon_value[HANGUL_KEYBOARD_VALUE_MOEUM] != NULL) {
        fprintf(f, " moeum-value=\""); emit_ucs_list(f, kb->addon_value[HANGUL_KEYBOARD_VALUE_MOEUM]); fprintf(f, "\"");
    }
    if (kb->addon_value[HANGUL_KEYBOARD_VALUE_SYMBOL] != NULL) {
        fprintf(f, " symbol-value=\""); emit_ucs_list(f, kb->addon_value[HANGUL_KEYBOARD_VALUE_SYMBOL]); fprintf(f, "\"");
    }
    if (kb->addon_value[HANGUL_KEYBOARD_VALUE_YETGEUL] != NULL) {
        fprintf(f, " yetgeul-value=\""); emit_ucs_list(f, kb->addon_value[HANGUL_KEYBOARD_VALUE_YETGEUL]); fprintf(f, "\"");
    }
    if (kb->addon_value[HANGUL_KEYBOARD_VALUE_EXTENDED_STEP] != NULL) {
        fprintf(f, " ext-step=\""); emit_ucs_list(f, kb->addon_value[HANGUL_KEYBOARD_VALUE_EXTENDED_STEP]); fprintf(f, "\"");
    }
    /* addon_func[SYMBOL] is a code pointer: re-bind via the symbol-func token. The
     * only expander the shin family uses is hangul_ascii_to_symbol_shin -> "shin". */
    if (kb->addon_func[HANGUL_FUNCTION_SYMBOL] != NULL)
        fprintf(f, " symbol-func=\"shin\"");
    fprintf(f, "/>\n\n");

    /* map[0] -- all 128 entries explicit (zeros included) for exactness. */
    fprintf(f, "    <map id=\"0\">\n");
    const ucschar* t = kb->table[0];
    for (unsigned k = 0; k < HANGUL_KEYBOARD_TABLE_SIZE; ++k) {
        ucschar v = (t != NULL) ? t[k] : 0;
        fprintf(f, "        <item key=\"0x%02x\" value=\"0x%04x\"/>\n", k, (unsigned)v);
    }
    fprintf(f, "    </map>\n\n");

    /* combination[0/1/2]. */
    emit_combination(f, kb->combination[0], 0);
    emit_combination(f, kb->combination[1], 1);
    emit_combination(f, kb->combination[2], 2);

    fprintf(f, "\n</hangul-keyboard>\n");
    fclose(f);
    return 1;
}

/* ---- VERIFY ---- */

static int cmp_combi_item(const void* a, const void* b)
{
    const HangulCombinationItem* x = a;
    const HangulCombinationItem* y = b;
    if (x->key != y->key) return (x->key < y->key) ? -1 : 1;
    if (x->code != y->code) return (x->code < y->code) ? -1 : 1;
    return 0;
}

/* Compare two combinations as sorted key/code multisets (loader sorts on load;
 * builtin static array is source-ordered). Returns 1 if identical. */
static int combi_equal(const HangulCombination* a, const HangulCombination* b, const char* tag)
{
    int an = (a != NULL) ? (int)a->size : -1;
    int bn = (b != NULL) ? (int)b->size : -1;
    if ((a == NULL) != (b == NULL)) {
        printf("    DIFF %s presence: builtin=%s xml=%s\n", tag,
               a ? "present" : "NULL", b ? "present" : "NULL");
        return 0;
    }
    if (a == NULL) return 1; /* both NULL */
    if (an != bn) {
        printf("    DIFF %s size: builtin=%d xml=%d\n", tag, an, bn);
        return 0;
    }
    if (an == 0) return 1;
    HangulCombinationItem* sa = malloc(sizeof(*sa) * an);
    HangulCombinationItem* sb = malloc(sizeof(*sb) * bn);
    memcpy(sa, a->table, sizeof(*sa) * an);
    memcpy(sb, b->table, sizeof(*sb) * bn);
    qsort(sa, an, sizeof(*sa), cmp_combi_item);
    qsort(sb, bn, sizeof(*sb), cmp_combi_item);
    int ok = 1;
    for (int i = 0; i < an; ++i) {
        if (sa[i].key != sb[i].key || sa[i].code != sb[i].code) {
            printf("    DIFF %s[%d]: builtin key=0x%08x code=0x%04x  xml key=0x%08x code=0x%04x\n",
                   tag, i, (unsigned)sa[i].key, (unsigned)sa[i].code,
                   (unsigned)sb[i].key, (unsigned)sb[i].code);
            ok = 0;
        }
    }
    free(sa); free(sb);
    return ok;
}

static int streq0(const char* a, const char* b)
{
    if (a == NULL && b == NULL) return 1;
    if (a == NULL || b == NULL) return 0;
    return strcmp(a, b) == 0;
}

static int ucs_list_equal(const ucschar* a, const ucschar* b)
{
    if ((a == NULL) != (b == NULL)) return 0;
    if (a == NULL) return 1;
    unsigned i = 0;
    for (; a[i] != 0 && b[i] != 0; ++i)
        if (a[i] != b[i]) return 0;
    return a[i] == b[i]; /* both terminate together */
}

/* Full-field byte-diff of the reloaded XML keyboard vs the builtin oracle.
 * Returns the number of differential fields (0 == byte-identical transcription). */
static int verify_one(const HangulKeyboard* oracle, const HangulKeyboard* xml)
{
    int diff = 0;

    if (xml == NULL) { printf("    DIFF load returned NULL\n"); return 1; }

    if (!streq0(oracle->id, xml->id)) {
        printf("    DIFF id: builtin=%s xml=%s\n", oracle->id, xml->id); ++diff;
    }
    if (oracle->type != xml->type) {
        printf("    DIFF type: builtin=%d xml=%d\n", oracle->type, xml->type); ++diff;
    }

    /* map[0] -- all 128 entries. */
    {
        int map_diff = 0;
        for (unsigned k = 0; k < HANGUL_KEYBOARD_TABLE_SIZE; ++k) {
            ucschar bv = (oracle->table[0] != NULL) ? oracle->table[0][k] : 0;
            ucschar xv = (xml->table[0]    != NULL) ? xml->table[0][k]    : 0;
            if (bv != xv) {
                if (map_diff < 8)
                    printf("    DIFF map[0][0x%02x]: builtin=0x%04x xml=0x%04x\n",
                           k, (unsigned)bv, (unsigned)xv);
                ++map_diff;
            }
        }
        if (map_diff) { printf("    map[0] differential entries=%d\n", map_diff); ++diff; }
    }

    if (!combi_equal(oracle->combination[0], xml->combination[0], "combination[0]")) ++diff;
    if (!combi_equal(oracle->combination[1], xml->combination[1], "combination[1]")) ++diff;
    if (!combi_equal(oracle->combination[2], xml->combination[2], "combination[2]")) ++diff;

    /* flag[5]. */
    for (int i = 0; i < 5; ++i) {
        if (oracle->flag[i] != xml->flag[i]) {
            printf("    DIFF flag[%d]: builtin=%d xml=%d\n", i, oracle->flag[i], xml->flag[i]);
            ++diff;
        }
    }

    /* addon_key[0..2] strings. */
    for (int i = 0; i < 3; ++i) {
        if (!streq0(oracle->addon_key[i], xml->addon_key[i])) {
            printf("    DIFF addon_key[%d]: builtin=%s xml=%s\n", i,
                   oracle->addon_key[i] ? oracle->addon_key[i] : "(null)",
                   xml->addon_key[i]    ? xml->addon_key[i]    : "(null)");
            ++diff;
        }
    }

    /* addon_value[0..3] ucschar arrays. */
    for (int i = 0; i < 4; ++i) {
        if (!ucs_list_equal(oracle->addon_value[i], xml->addon_value[i])) {
            printf("    DIFF addon_value[%d] mismatch\n", i);
            ++diff;
        }
    }

    /* addon_func[SYMBOL] presence (code pointer; same binding expected). */
    if ((oracle->addon_func[HANGUL_FUNCTION_SYMBOL] != NULL) !=
        (xml->addon_func[HANGUL_FUNCTION_SYMBOL] != NULL)) {
        printf("    DIFF addon_func[SYMBOL] presence: builtin=%d xml=%d\n",
               oracle->addon_func[HANGUL_FUNCTION_SYMBOL] != NULL,
               xml->addon_func[HANGUL_FUNCTION_SYMBOL] != NULL);
        ++diff;
    }
    /* When both present, the shin family binds the same expander (only "shin"
     * is in the registry for these ids), so a pointer-equality check is exact. */
    if (oracle->addon_func[HANGUL_FUNCTION_SYMBOL] != NULL &&
        xml->addon_func[HANGUL_FUNCTION_SYMBOL] != NULL &&
        oracle->addon_func[HANGUL_FUNCTION_SYMBOL] != xml->addon_func[HANGUL_FUNCTION_SYMBOL]) {
        printf("    DIFF addon_func[SYMBOL] pointer differs\n");
        ++diff;
    }

    return diff;
}

int main(int argc, char** argv)
{
    /* engine root = shared\engine ; body keyboards live at repo root\shared\data\keyboards */
    const char* dir = (argc > 1) ? argv[1] : "../data/keyboards";
    printf("# shin external-XML byte-fidelity verifier (B2)\n");
    printf("# dir=%s\n", dir);

    int gen_ok = 0, verify_ok = 0;

    /* ---- (GEN) emit each XML from the builtin oracle. ---- */
    printf("\n=== GEN ===\n");
    for (unsigned i = 0; i < NSHIN; ++i) {
        const HangulKeyboard* kb = nabicloud_shin_builtin_by_id(kIds[i]);
        if (kb == NULL) { printf("  GEN FAIL oracle missing id=%s\n", kIds[i]); continue; }
        if (gen_one(dir, kb)) { ++gen_ok; printf("  GEN ok %s\n", kIds[i]); }
    }

    /* ---- (VERIFY) reload + full-field byte-diff. ---- */
    printf("\n=== VERIFY (differential per id; 0 == byte-identical) ===\n");
    for (unsigned i = 0; i < NSHIN; ++i) {
        const HangulKeyboard* oracle = nabicloud_shin_builtin_by_id(kIds[i]);
        char path[512];
        snprintf(path, sizeof(path), "%s/%s.xml", dir, kIds[i]);
        HangulKeyboard* xml = hangul_keyboard_new_from_file(path);
        printf("\n--- %s ---\n", kIds[i]);
        int diff = verify_one(oracle, xml);
        printf("  differential=%d %s\n", diff, diff == 0 ? "BYTE_IDENTICAL" : "MISMATCH");
        if (diff == 0) ++verify_ok;
        if (xml != NULL) hangul_keyboard_delete(xml);
    }

    /* ---- (DIR) prove the 9 ids auto-register as external keyboards. ---- */
    printf("\n=== directory scan (external registration) ===\n");
    unsigned loaded = hangul_keyboard_list_load_dir(dir);
    int dir_ok = 0;
    for (unsigned i = 0; i < NSHIN; ++i) {
        const HangulKeyboard* kb = hangul_keyboard_list_get_keyboard(kIds[i]);
        int ok = (kb != NULL);
        printf("  %-14s registered=%s type=%d %s\n", kIds[i],
               kb ? "yes" : "no", kb ? kb->type : -1, ok ? "OK" : "FAIL");
        if (ok) ++dir_ok;
    }
    printf("  (load_dir returned list size=%u)\n", loaded);

    printf("\n# summary: gen=%d/%d verify(differential==0)=%d/%d dir-register=%d/%d\n",
           gen_ok, (int)NSHIN, verify_ok, (int)NSHIN, dir_ok, (int)NSHIN);
    int all = (gen_ok == (int)NSHIN && verify_ok == (int)NSHIN && dir_ok == (int)NSHIN);
    printf("# %s\n", all ? "SHIN_XML_ALL_PASS" : "SHIN_XML_FAIL");
    printf("# end\n");
    return all ? 0 : 1;
}
